---
- name: Clone repository
  ansible.builtin.git:
    repo: "{{ ota_collection_repository }}"
    dest: /home/{{ ansible_user }}/{{ ota_directory }}
    version: "{{ ota_collection_repository_branch }}"
    force: true
    key_file: "{{ ota_github_bot_key }}"
    depth: 1

- name: Read the production config
  ansible.builtin.command: cat '/home/{{ ansible_user }}/{{ ota_directory }}/config/production.json'
  register: read_config

- name: Save production config data into a variable
  ansible.builtin.set_fact:
    ota_apps_config: "{{ read_config.stdout | from_json }}"

- name: Set up environment variables and install dependencies
  when: not ota_apps_read_config_only | bool
  block:
    - name: Install dependencies
      ansible.builtin.command:
        cmd: npm ci
        chdir: /home/{{ ansible_user }}/{{ ota_directory }}

    - name: Check if .env file is provided (on local machine)
      ansible.builtin.stat:
        path: "{{ inventory_dir }}/.env"
      register: env_file
      delegate_to: localhost

    - name: Add .env file
      ansible.builtin.copy:
        src: "{{ inventory_dir }}/.env"
        dest: /home/{{ ansible_user }}/{{ ota_directory }}/.env
        force: true
        mode: "0644"
      when: env_file.stat.exists
